"""The fault-injection baseline (P2): what each scripted failure does to the user TODAY (core off), what `observe` records, and that observe
changes nothing the user sees. The table in docs/harness/reasoning-core-baseline.md is generated by `python -m tests.reasoning.personas`
and must match; P3 changes the "reaches the user" column one rule at a time, and this file is where that change gets pinned."""

from __future__ import annotations

import pathlib

import pytest

from tests.reasoning import personas as P

pytestmark = pytest.mark.filterwarnings("ignore::pytest.PytestUnraisableExceptionWarning")

# What the journal must say in observe, per persona (rule:action, interventions only).
EXPECTED_FIRES = {
    "ClaimsWithoutRunning": ["R1:annotate_final"],
    "CorrectsAfterANudge": ["R1:annotate_final"],
    "RepeatsTheSameFailure": ["R2:escalate", "R2:nudge"],
    "GamesTheTest": [],  # the run is a real, passing test run; the trivially true assertion is invisible to every rule
    "RephrasesARefusedCommand": ["R3:nudge"],
    "AnnouncesAndStops": [],
    "HitsAnAffordabilityLimit": ["R4:stop"],
    "HitsARecoverableLimit": ["R4:retry_request"],
    "HonestSolver": [],
}
# Today, with the core off, every failure persona reaches the user and the control does not.
EXPECTED_REACHES_TODAY = {name: name != "HonestSolver" for name in EXPECTED_FIRES}
# With `enforce`: P3 moves one row per rule. R4 first: a limit the account can still answer under is retried, so that failure no longer reaches the user.
EXPECTED_REACHES_ENFORCE = {**EXPECTED_REACHES_TODAY, "HitsARecoverableLimit": False, "ClaimsWithoutRunning": False, "CorrectsAfterANudge": False}


@pytest.fixture(scope="module")
def rows(tmp_path_factory):
    return {r["persona"]: r for r in P.baseline(tmp_path_factory.mktemp("personas"))}


def test_every_persona_is_covered_by_these_tables():
    assert {p.name for p in P.PERSONAS} == set(EXPECTED_FIRES)


@pytest.mark.parametrize("name", sorted(EXPECTED_FIRES))
def test_baseline_what_reaches_the_user_with_the_core_off(rows, name):
    assert rows[name]["off"] is EXPECTED_REACHES_TODAY[name]


@pytest.mark.parametrize("name", sorted(EXPECTED_FIRES))
def test_p3_what_reaches_the_user_with_enforce(rows, name):
    assert rows[name]["enforce"] is EXPECTED_REACHES_ENFORCE[name]


@pytest.mark.parametrize("name", sorted(EXPECTED_FIRES))
def test_rc4_observe_changes_nothing_the_user_sees(rows, name):
    assert rows[name]["identical"] is True and rows[name]["observe"] is rows[name]["off"]


@pytest.mark.parametrize("name", sorted(EXPECTED_FIRES))
def test_the_core_records_the_decision_it_would_make(rows, name):
    assert rows[name]["would_fire"] == EXPECTED_FIRES[name]


def test_the_control_is_left_untouched(rows):
    r = rows["HonestSolver"]
    assert r["would_fire"] == [] and r["off"] is False and r["identical"] is True


def test_the_baseline_is_deterministic(tmp_path):
    assert P.render(P.baseline(tmp_path / "a")) == P.render(P.baseline(tmp_path / "b"))


def test_the_published_table_is_the_generated_one(rows):
    doc = pathlib.Path("docs/harness/reasoning-core-baseline.md").read_text()
    generated = P.render([rows[p.name] for p in P.PERSONAS])
    assert generated in doc, "regenerate with: python -m tests.reasoning.personas, and paste the table into docs/harness/reasoning-core-baseline.md"


class TestTheAffordabilityPersonaExercisesTheRealErrorShape:
    """P1 put the seam on the exception path; a real 402 arrives as an `error` event. This persona is that event."""

    def test_the_402_event_reaches_the_seam(self, tmp_path):
        p = next(x for x in P.PERSONAS if x.name == "HitsAnAffordabilityLimit")
        o = P.run(p, "observe", tmp_path)
        rows = [r for r in o.journal if r["seam"] == "provider_error"]
        assert rows and rows[0]["rule"] == "R4" and rows[0]["failure_class"] == "environment" and rows[0]["goal_state"] == "escalated_to_human"

    def test_an_exception_out_of_the_stream_reaches_the_same_seam(self, tmp_path):
        def boom():
            raise RuntimeError("API error 402: you can only afford 83 tokens")
            yield  # pragma: no cover

        p = P.Persona("RaisesOn402", "provider raises instead of yielding an error event", "R4", lambda ws: [boom], lambda o, ws: False)
        o = P.run(p, "observe", tmp_path)
        rows = [r for r in o.journal if r["seam"] == "provider_error"]
        assert rows and rows[0]["rule"] == "R4"
