#!/usr/bin/env python3
"""Derive `CURRENT_AUTHORITIES.md` from the arbiter, the ADR log and the tree.

**Why committed.** ADR-0062 R8 (finding **F113**): a derived page must have a committed
generator. This page founded the pattern and was the one register regenerated by hand — a
manual §6 procedure, which is **F75**'s class: *"an instrument that cannot be committed is not
a re-runnable measurement."*

**What is derived, what is checked, and what is data.**

* **Derived.** The header's commit, date and ADR range (from `git` and the ADR log — **F97**);
  §3's rows and results (from `goal.PRECEDENCE`, read at render time); §3's code pins (from
  `derive_goal_state`'s AST — the `if` that carries each `# row N` marker, row 0's
  `already_recorded` guard, and the final `return`).
* **Checked, and refused when wrong.** Every `path:line` pin must be in range, non-blank, and
  name — within ±2 lines — an identifier its own line's prose names. Each §3 row's branch must
  return the `GoalState` member `PRECEDENCE` states, and `derive_goal_state` driven with that
  row's inputs must return it too. Each authority's ADR chain must cite only ADRs that exist
  and are not `SUPERSEDED`, and must include every ADR the log's index says *supersedes* or
  *replaces* one it cites (clause-scoped: `ADR-0043` superseding `ADR-0041 R3/R7` binds a chain
  that cites `ADR-0041 R3/R7`, not one citing `ADR-0041 R1`).
* **Data.** The prose — each authority's owner, what it cannot decide, its ADR chain and its
  record fields; §2's aggregation; §3's conditions and sources; §4. Transcribed, with its pins
  checked on every run.
* **Append-only.** `SECTION_5` is the page's own record of what it could not pin. It is emitted
  unchanged; a new finding is appended here, and a decided one is marked `DECIDED` with its ADR.
  The generator never writes a finding.

Run: `env -u PYTHONPATH .venv/bin/python scripts/derive_current_authorities.py`
"""
from __future__ import annotations

import ast
import pathlib
import re
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
OUT = REPO / "CURRENT_AUTHORITIES.md"
DECISIONS = REPO / "WISP_ARCHITECTURE_DECISIONS.md"
GOAL_PY = REPO / "wisp" / "core" / "goal.py"

PIN_RE = re.compile(r"`([A-Za-z0-9_./-]+\.py):(\d+)(?:-(\d+))?`")
IDENT_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]{3,}")
PIN_WINDOW = 2

#: `(heading, current owner, cannot decide, current ADRs, durable record fields)`.
AUTHORITIES: list[tuple[str, str, str, str, str]] = [
    ("1.1 turn predicate",
     "`goal.terminal_outcome_from_evidence` (`wisp/core/goal.py:132`); `turn_succeeded` is a "
     "**projection** of it, computed once per turn (`wisp/core/runtime.py:999`)",
     "goal state · recovery · verification",
     "**ADR-0035** §Decision 2 (turn level remains terminal evidence) → **ADR-0044** R1/R2 (the "
     "*only* implementation; the flag is a projection) → **ADR-0047** R2 (no longer an "
     "arbitration input; still recorded)",
     "`terminal_outcome`, `turn_succeeded` — the goal-state record (`wisp/core/runtime.py:1342`, "
     "`wisp/core/runtime.py:1357`); `terminal_outcome`, `turn_succeeded` — the attempt journal "
     "line `{\"kind\":\"attempt\"}` (`wisp/core/convergence.py:1327`)"),
    ("1.2 stream state",
     "`guarded_provider_stream` (`wisp/core/provider_stream.py:122`); the two facts are "
     "`got_meaningful` (`wisp/core/provider_stream.py:150`) and `saw_terminal` "
     "(`wisp/core/provider_stream.py:151`)",
     "turn success · acceptance · goal state",
     "**ADR-0039** R5 (the guard owns *recovery*, not canonicalization; it reads the "
     "normalization boundary) → **ADR-0041** R3/R7 — **superseded** by **ADR-0043** R1–R7 "
     "(payload-based meaningfulness for every type; the classifier owns no vocabulary but "
     "`TERMINAL_TYPES`)",
     "**none.** It is an in-flight guard, not a recorded fact: its output is consumed by the "
     "turn predicate within the same turn. Nothing replays it, so there is nothing to journal — "
     "stated so a reader does not go looking for a key that does not exist"),
    ("1.3 acceptance verdict",
     "`acceptance.evaluate` (`wisp/core/acceptance.py:213`)",
     "goal state · recovery · **whether to gate** (the gate is a separate, flag-controlled "
     "consumer)",
     "**ADR-0016** (two stages; stage 3a does not gate) · **ADR-0017** (the floor criterion is "
     "an *implication*) · **ADR-0018** (the engine publishes the guard; the runtime only reads "
     "it) · **ADR-0042** (the verdict is an **input**, not a second authority)",
     "`verdict` in the verdict envelope (ADR-0013, `wisp/core/acceptance.py:204`) · "
     "`acceptance_verdict` in the goal-state record (`wisp/core/runtime.py:1343`) · `verdict`, "
     "`unmet`, `evidence_ids` in the attempt journal (`wisp/core/convergence.py:1337-1338`)"),
    ("1.4 progress verdict",
     "`progress.evaluate_progress` (`wisp/core/progress.py:155`); verdicts `NO_PROGRESS` / "
     "`MEANINGFUL_PROGRESS` / `PROGRESS_UNDETERMINABLE` (`wisp/core/progress.py:50-63`)",
     "acceptance · goal state · **which rung**",
     "**ADR-0046** R1–R11 (a second *input* to the recovery decision, not a re-classification of "
     "the failure) → **ADR-0047** R6 (it is the witness that the state changed) and R8 (a "
     "regression, a tampered input, or an unmeasurable attempt cannot unlock it)",
     "`progress`, `progress_signals` (`wisp/core/convergence.py:1305-1306`, "
     "`wisp/core/convergence.py:1344-1345`) · `measurement_observations` + `measurement_digest` "
     "— the raw payloads, digested over `WITNESS_FIELDS` only (F63; "
     "`wisp/core/convergence.py:1192-1205`)"),
    ("1.5 goal state",
     "`goal.derive_goal_state` (`wisp/core/goal.py:146`); the contract as data is "
     "`goal.PRECEDENCE` (`wisp/core/goal.py:108-117`), 8 rows",
     "recovery rung · **whether `done` was withheld**",
     "**ADR-0035** (the contract; rows 0–6) → **ADR-0036** (amends ADR-0035 by reconciling its "
     "two clauses; adds the predicate to the goal record) → **ADR-0037** (completes ADR-0036) → "
     "**ADR-0042** (states the relation ADR-0035 left implicit; no behaviour change) → "
     "**ADR-0044** (removes the duplicated predicate) → **ADR-0047** R1–R5 (rows 3–6 revised) → "
     "**ADR-0049** (makes this table canonical at eight rows; resolves older numbering by "
     "content; ratifies two cells)",
     "`SessionEvent.goal_state_event` (`wisp/core/runtime.py:1339`), 9 keys: `goal_state`, "
     "`terminal_outcome`, `acceptance_verdict`, `stagnation_verdict`, "
     "`stagnation_allows_goal_met`, `turn_succeeded`, `cancelled`, `escalated`, `failure_code` "
     "(`wisp/core/runtime.py:1341-1362`). **`stagnation_allows_goal_met` is the one replay must "
     "read** — `stagnation_verdict` ignores `trap_fired` (F35, ADR-0036 §6)"),
    ("1.6 recovery ladder state",
     "`RecoveryLadder.ladder_state` (`wisp/core/recovery.py:775`) — **renamed** from "
     "`terminal_outcome`",
     "completion · goal state",
     "**ADR-0024** (denial enforced by CLASS) · **ADR-0025** (an unsafe rollback escalates) · "
     "**ADR-0026** (a mechanism, not yet consulted by the turn loop) → **ADR-0044** R6 (the "
     "rename, which removed a cross-layer name collision) → **ADR-0046** (progress widens one "
     "class's legal rungs) → **ADR-0047** R6–R13 (R5's unit is the *strategy*, not the rung)",
     "`RecoveryDecision.seq` and `ladder_history` (`wisp/core/recovery.py:574`, "
     "`wisp/core/recovery.py:589`) · `AttemptRecord.rung`, `.directive`, `.failure_class` "
     "(`wisp/core/convergence.py:1277-1278`, `wisp/core/convergence.py:1299`) · "
     "`BudgetGovernor.snapshot()` — reports `productive_continuations` "
     "(`wisp/core/recovery.py:505`)"),
]

CHAIN_DIAGRAM = """\
```
provider terminal → stream state → turn predicate → acceptance verdict
                                                    ↘ progress verdict ↘
                                                        goal state → recovery ladder state
```"""

SECTION_2 = """\
## 2. (a) The run-level aggregation — stated once

> **A run's state is the ladder's escalation if it surrendered, otherwise the last attempt's derived state.**

Source: **ADR-0047 R13**; `goal.derive_goal_state`'s row 2 consumes `escalated` (`wisp/core/goal.py:195`), and the
convergence loop reads the last `AttemptRecord.goal_state` (`wisp/core/convergence.py:1281`). This is the *only*
place the aggregation is stated; a second statement would be a second authority for one question."""

#: `row -> (condition, source)`. The row set and each row's result come from `goal.PRECEDENCE`;
#: the code pin is appended from `derive_goal_state`'s AST.
MATRIX: dict[int, tuple[str, str]] = {
    0: ("a terminal state is already recorded", "ADR-0035 row 0 / ADR-0020"),
    1: ("operator cancellation", "ADR-0035 row 1"),
    2: ("ladder exhausted", "ADR-0035 row 2"),
    3: ("`A` = `FAIL`", "ADR-0035 row 3 (clause split by ADR-0047 R1)"),
    4: ("`T` = `FAILED` **and no `A` = `PASS`**", "**ADR-0047 R1**"),
    5: ("`S` — `may_report_goal_met()` is `False`", "ADR-0035 row 4"),
    6: ("`A` = `PASS`", "ADR-0035 row 6"),
    7: ("otherwise — no decisive verdict", "fall-through, code only — **ADR-0049 R1**"),
}

#: The inputs that select each row, driven through `derive_goal_state` by `_matrix_problems`.
SELECTORS: dict[int, dict] = {
    1: dict(terminal_outcome="succeeded", cancelled=True),
    2: dict(terminal_outcome="succeeded", escalated=True),
    3: dict(terminal_outcome="succeeded", acceptance_verdict="fail"),
    4: dict(terminal_outcome="failed", acceptance_verdict=None),
    5: dict(terminal_outcome="succeeded", acceptance_verdict="pass", stagnating=True),
    6: dict(terminal_outcome="succeeded", acceptance_verdict="pass"),
    7: dict(terminal_outcome="succeeded", acceptance_verdict=None),
}

MATRIX_AFTER = """\
**The input combination F60 moved is row 4's qualifier: `T` = `FAILED` + `A` = `PASS` was `GOAL_FAILED`,
and is now `GOAL_MET`.** That is the change ADR-0047 R1 documents, and it is the reason `turn_succeeded`
stopped arbitrating (R2). **Two further cells moved and ADR-0047 does not state them — both are ratified
by ADR-0049** (R2: `INCOMPLETE`+`PASS` → `GOAL_MET`; R3: `fatal`+`PASS`+`stagnating` → `GOAL_STAGNATED`).
See §5 F-1.

**The rules the row order cannot express.** `fatal > stagnation`, `stagnation > PASS`, `PASS > fatal` is a
**cycle**, so no ordering of rows can express it (ADR-0047 R3). It is broken where it is semantically
broken: row 4 is the only clause whose *meaning* depends on the verdict, because it is the only one about
the **attempt** rather than the **objective**."""

SECTION_4 = """\
## 4. What is *not* in this page

- **Enforcement.** Every flag above defaults **OFF** — `goal_state`/`WISP_GOAL_STATE`,
  `recovery_ladder`/`WISP_RECOVERY_LADDER`, `stagnation_gate`/`WISP_STAGNATION_GATE` (ADR-0035 §9;
  ADR-0037). This page describes *semantics*; enablement was ADR-0016's question, and **ADR-0051
  replaced its condition** with a precondition on the criteria set (satisfied by ADR-0053) plus a
  declared-population measure. M1's state is **`PARTIAL`** — the mechanism is built and driven, and
  the population is short by one capable model (ADR-0054). *(Corrected 2026-09-25: this line said
  "remains `NOT_YET_DETERMINABLE`" until the authorization-parity phase, which is after ADR-0051
  superseded it. The page's guard checks `path:line` pins, not prose, so it could not catch it.)*
- **History.** Why a row reads the way it does is in the ADR, not here.
- **The graph.** `core/task_graph.py` journals per-turn node status; `runtime.py` states plainly that it
  is *"RECORDED, not enforced"*. It is a consumer of the turn predicate, not an authority over it."""

#: **Append-only.** The page's own findings. Emitted unchanged; never written by the generator.
SECTION_5 = """\
## 5. This page's own findings, and where they were decided

§5 exists because a derived page may **state** the current state but may not **decide** it. Both claims
below were recorded here as findings and have since been decided — the resolution is cited, not
re-argued, because a page that re-argued a decision would be a second authority for it.

**F-1 — DECIDED (ADR-0049 R2/R3).** *The arbitration had moved further than ADR-0047 stated.*
ADR-0047 R1 said *"Only one input combination moved"*; a differential against `b9af5f0^` over all 48
input combinations found **7 cells changed in three semantic classes** — two documented, and two not:
`INCOMPLETE`+`PASS` → `GOAL_MET` (was `GOAL_UNVERIFIED`), and `fatal`+`PASS`+`stagnating` →
`GOAL_STAGNATED` (was `GOAL_FAILED`).
**ADR-0049 R2 ratifies the first** (the objective's evidence decides where it is decisive — ADR-0047's own
principle, applied to `INCOMPLETE` rather than `FAILED`), and **ADR-0049 R3 scopes the second** (a fatal
error *with* a `PASS` is not fatal, so the cell reduces to `PASS` + stagnation, which is row 5).
The measured routing is in `tests/reliability/test_precedence_canonical.py::TestTheRatifiedCells`.

**F-2 — DECIDED (ADR-0049 R1).** *The precedence table was total only in the code, and "row N" was
ambiguous between two ADRs and the implementation.* ADR-0035's arbiter had rows **0–6** and no
fall-through; the code has always had a row 7.
**ADR-0049 R1 makes `goal.PRECEDENCE` (`wisp/core/goal.py:108-117`, eight rows 0–7) the canonical table**
and declares every older numbering **historical**, to be resolved against it **by content**. The
resolution rule is §3's table plus ADR-0049's §Resolution rules; the mapping is pinned by
`tests/reliability/test_precedence_canonical.py::TestTheContentMappingIsReproducible`, which drives
ADR-0035's conditions over the full input space and reports which canonical row answers each one.

**No open findings.** A future conflict between two ADRs is recorded here and stops — it is never
resolved on this page.
"""

SECTION_6 = """\
## 6. Regeneration procedure

1. Change an ADR, or move code a pin names. 2. Re-pin in the generator's data — **never on this page**.
3. Run `env -u PYTHONPATH .venv/bin/python scripts/derive_current_authorities.py`. It **refuses, and
writes nothing**, if a pin no longer names its symbol, if a §3 row's branch does not return what
`goal.PRECEDENCE` states, or if an authority's ADR chain cites an ADR the log supersedes without citing
the ADR that supersedes it. 4. §3 is generated from the code; there is no table to edit.
5. Any claim that no longer pins becomes a new finding appended to `SECTION_5` in the generator; a
finding is never deleted, and a decided one is marked `DECIDED` with its ADR."""

_NUMBER_WORDS = {6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten"}


# ── sources ────────────────────────────────────────────────────────────────

def _git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=REPO, capture_output=True, text=True,
                          check=True).stdout.strip()


def _decisions_text() -> str:
    return DECISIONS.read_text(encoding="utf-8")


def _defined_adrs(text: str) -> set[int]:
    return {int(n) for n in re.findall(r"^## ADR-(\d{4})\b", text, re.M)}


def _index_rows(text: str) -> dict[int, str]:
    """ADR number → its Decision-index Status cell (and everything after it)."""
    idx = text.split("## Decision index", 1)[1] if "## Decision index" in text else ""
    rows: dict[int, str] = {}
    for line in idx.splitlines():
        m = re.match(r"^\| (\d{4}) \|", line)
        if m:
            rows[int(m.group(1))] = "|".join(line.split("|")[4:])
    return rows


def _clauses(spec: str) -> set[int] | None:
    """`R3/R7` → {3, 7}; `R6–R13` → {6..13}; no R-clause → None (the whole ADR)."""
    spec = spec.strip()
    if not spec.startswith("R"):
        return None
    out: set[int] = set()
    for part in spec.split("/"):
        m = re.fullmatch(r"R(\d+)(?:[–-]R?(\d+))?", part.strip())
        if not m:
            return None
        lo, hi = int(m.group(1)), int(m.group(2) or m.group(1))
        out.update(range(lo, hi + 1))
    return out


_CLAUSE = r"((?:R\d+(?:[–-]R?\d+)?)(?:/R\d+(?:[–-]R?\d+)?)*)"


def _supersessions(text: str) -> list[tuple[int, int, set[int] | None]]:
    """`(superseder, superseded, clauses)` from the index's Status cells."""
    out = []
    for adr, status in _index_rows(text).items():
        for m in re.finditer(rf"(?:supersedes|replaces) ADR-(\d{{4}})(?:\s+{_CLAUSE})?", status):
            out.append((adr, int(m.group(1)), _clauses(m.group(2) or "")))
    return out


def _goal_tree() -> ast.FunctionDef:
    tree = ast.parse(GOAL_PY.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == "derive_goal_state":
            return node
    raise LookupError("wisp/core/goal.py defines no derive_goal_state")


def _precedence_span() -> tuple[int, int]:
    for node in ast.parse(GOAL_PY.read_text(encoding="utf-8")).body:
        target = getattr(node, "target", None) or (getattr(node, "targets", None) or [None])[0]
        if isinstance(target, ast.Name) and target.id == "PRECEDENCE":
            return node.lineno, node.end_lineno or node.lineno
    raise LookupError("wisp/core/goal.py defines no PRECEDENCE")


def _returned_member(body: list[ast.stmt]) -> str | None:
    """The `GoalState.<member>` a branch returns, or None."""
    for stmt in body:
        if (isinstance(stmt, ast.Return) and isinstance(stmt.value, ast.Attribute)
                and isinstance(stmt.value.value, ast.Name) and stmt.value.value.id == "GoalState"):
            return stmt.value.attr
    return None


def _branches() -> dict[int, tuple[str, str | None]]:
    """Row → (pin, the `GoalState` member its branch returns), read from the AST.

    Rows 1–6 are the `if` statements carrying a `# row N` marker; row 0 is the `if` that tests
    `already_recorded`; row 7 is the function's final `return`.
    """
    fn = _goal_tree()
    lines = GOAL_PY.read_text(encoding="utf-8").splitlines()
    out: dict[int, tuple[str, str | None]] = {}
    for stmt in fn.body:
        if not isinstance(stmt, ast.If):
            continue
        names = {n.id for n in ast.walk(stmt.test) if isinstance(n, ast.Name)}
        if "already_recorded" in names:
            out[0] = (f"wisp/core/goal.py:{stmt.lineno}-{stmt.end_lineno}", None)
            continue
        m = re.search(r"#\s*row\s+(\d+)\b", lines[stmt.lineno - 1])
        if m:
            out[int(m.group(1))] = (f"wisp/core/goal.py:{stmt.lineno}",
                                    _returned_member(stmt.body))
    last = fn.body[-1]
    if isinstance(last, ast.Return):
        out[7] = (f"wisp/core/goal.py:{last.lineno}", _returned_member([last]))
    return out


def _precedence():
    sys.path.insert(0, str(REPO))
    from wisp.core import goal

    return goal.PRECEDENCE


# ── checks — each returns a list of problems; empty means sound ────────────

def _pin_problems(text: str) -> list[str]:
    """The guard's pin rule, applied before writing: in range, non-blank, names its symbol."""
    path_noise = {m for path, _s, _e in PIN_RE.findall(text) for m in IDENT_RE.findall(path)}
    problems: list[str] = []
    pins = checkable = 0
    for page_line, raw in enumerate(text.splitlines(), 1):
        found = PIN_RE.findall(raw)
        if not found:
            continue
        spans = [s for s in re.findall(r"`([^`]+)`", raw) if not PIN_RE.fullmatch(f"`{s}`")]
        expected = {m for s in spans for m in IDENT_RE.findall(s)} - path_noise
        for path, start, end in found:
            pins += 1
            f = REPO / path
            if not f.exists():
                problems.append(f"{path}:{start} — no such file (page line {page_line})")
                continue
            lines = f.read_text(encoding="utf-8").splitlines()
            lo, hi = int(start), int(end) if end else int(start)
            if lo < 1 or hi > len(lines) or hi < lo:
                problems.append(f"{path}:{start} — out of range (page line {page_line})")
                continue
            if not lines[lo - 1].strip():
                problems.append(f"{path}:{start} — the pinned line is blank")
                continue
            if not expected:
                continue
            checkable += 1
            window = " ".join(lines[max(0, lo - 1 - PIN_WINDOW):hi + PIN_WINDOW])
            if not any(name in window for name in expected):
                problems.append(f"{path}:{start} — none of {sorted(expected)} within "
                                f"±{PIN_WINDOW} lines (page line {page_line})")
    if pins < 30 or checkable < 15:
        problems.append(f"only {pins} pins / {checkable} content-checkable — the pin grammar "
                        "drifted and the check has gone vacuous")
    return problems


def _matrix_problems(precedence) -> list[str]:
    """`PRECEDENCE` against the arbiter's own branches, and against the arbiter driven."""
    sys.path.insert(0, str(REPO))
    from wisp.core.goal import GoalState, TerminalOutcome, derive_goal_state

    problems: list[str] = []
    rows = [r[0] for r in precedence]
    if rows != list(range(len(rows))) or len(rows) < 2:
        problems.append(f"PRECEDENCE's rows are not 0..n contiguous: {rows}")
    if set(rows) != set(MATRIX):
        problems.append(f"the page's conditions cover rows {sorted(MATRIX)}; "
                        f"PRECEDENCE has {rows}")
    branches = _branches()
    if set(branches) != set(rows):
        problems.append(f"derive_goal_state's branches mark rows {sorted(branches)}; "
                        f"PRECEDENCE has {rows}")
    for n, _cond, result in precedence:
        if n == 0:
            if not result.startswith("frozen"):
                problems.append(f"row 0's result is {result!r}; the arbiter freezes row 0")
            continue
        member = branches.get(n, (None, None))[1]
        if member != result:
            problems.append(f"row {n}: PRECEDENCE says {result}; the branch returns {member}")
        if n in SELECTORS:
            kwargs = dict(SELECTORS[n])
            kwargs["terminal_outcome"] = TerminalOutcome(kwargs["terminal_outcome"])
            got = derive_goal_state(**kwargs).name
            if got != result:
                problems.append(f"row {n}: PRECEDENCE says {result}; driven, the arbiter "
                                f"returns {got}")
    frozen = derive_goal_state(terminal_outcome=TerminalOutcome.FAILED,
                               already_recorded=GoalState.GOAL_MET)
    if frozen is not GoalState.GOAL_MET:
        problems.append("row 0: a recorded state is no longer frozen")
    return problems


def _chain_problems(authorities) -> list[str]:
    """Each chain resolves: its ADRs exist, none is SUPERSEDED, and none is superseded
    by an ADR the chain omits."""
    text = _decisions_text()
    defined = _defined_adrs(text)
    index = _index_rows(text)
    supersessions = _supersessions(text)
    problems: list[str] = []
    for heading, _o, _c, adrs, _f in authorities:
        cited: dict[int, set[int] | None] = {}
        for m in re.finditer(rf"\*\*ADR-(\d{{4}})\*\*(?:\s+{_CLAUSE})?", adrs):
            n, cl = int(m.group(1)), _clauses(m.group(2) or "")
            prev = cited.get(n, set())
            cited[n] = None if (cl is None or prev is None) else prev | cl
        if not cited:
            problems.append(f"§{heading}: the chain cites no ADR")
        for n in cited:
            if n not in defined:
                problems.append(f"§{heading}: ADR-{n:04d} does not exist")
            elif index.get(n, "").strip().upper().startswith("SUPERSEDED"):
                problems.append(f"§{heading}: ADR-{n:04d} is SUPERSEDED in the index")
        for by, old, cl in supersessions:
            if old not in cited or by in cited:
                continue
            mine = cited[old]
            if cl is not None and mine is not None and not (cl & mine):
                continue
            problems.append(f"§{heading}: cites ADR-{old:04d}, which ADR-{by:04d} supersedes, "
                            f"and does not cite ADR-{by:04d}")
    return problems


def _cell_problems() -> list[str]:
    cells = [c for a in AUTHORITIES for c in a] + [c for pair in MATRIX.values() for c in pair]
    return [f"a cell contains `|`: {c[:60]!r}" for c in cells if "|" in c]


def _check() -> list[str]:
    problems = _cell_problems() + _matrix_problems(_precedence()) + _chain_problems(AUTHORITIES)
    if "**F-" not in SECTION_5:
        problems.append("SECTION_5 carries no finding — §5 is append-only and may not be emptied")
    return problems + _pin_problems(render())


# ── rendering ──────────────────────────────────────────────────────────────

def _result_cell(result: str) -> str:
    if re.fullmatch(r"[A-Z_]+", result):
        return f"`{result}`"
    m = re.fullmatch(r"(\w+)(.*?)\s*\(ADR-\d{4}\)", result)
    return f"**{m.group(1)}**{m.group(2)}" if m else result


def render_matrix() -> str:
    precedence = _precedence()
    branches = _branches()
    lo, hi = _precedence_span()
    count = _NUMBER_WORDS.get(len(precedence), str(len(precedence)))
    L = [
        "## 3. (b) The precedence matrix",
        "",
        "Generated from `goal.PRECEDENCE` (each row and its result) and `derive_goal_state` (each code pin),",
        "following **ADR-0035**'s ordered arbiter as revised by **ADR-0047** R1.",
        "`T` = terminal outcome, `A` = the P3 acceptance verdict, `S` = the P7 stagnation predicate.",
        "",
        "| # | Condition | Result | Source |",
        "|---|---|---|---|",
    ]
    for n, _cond, result in precedence:
        condition, source = MATRIX.get(n, ("—", "—"))
        pin = branches.get(n, ("—", None))[0]
        L.append(f"| {n} | {condition} | {_result_cell(result)} | {source} · `{pin}` |")
    L += [
        "",
        f"**This table is canonical by ADR-0049 R1** — `goal.PRECEDENCE` (`wisp/core/goal.py:{lo}-{hi}`), {count} rows.",
        "ADR-0035 §Precedence's rows 0–6 and ADR-0047's renumbering are **historical**: resolve any \"row N\" against",
        "this table **by content**, not by number. ADR-0035's row 4 is stagnation (this table's row 5); ADR-0047",
        "R1's \"Row 4\" is the fatal clause (this table's row 4) — **different rows**. Full restatement, the mapping",
        "and the resolution rules are in **ADR-0049**.",
        "",
        MATRIX_AFTER,
    ]
    return "\n".join(L)


def _stamp():
    """The shared, squash-proof stamp helper (scripts/_page_stamp.py), loaded by path so it works however this script is run."""
    import importlib.util

    spec = importlib.util.spec_from_file_location("_page_stamp", pathlib.Path(__file__).with_name("_page_stamp.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def render() -> str:
    stamp = _stamp()
    sha = stamp.stamp_sha(REPO)  # the merge-base with origin/main: a squash merge cannot orphan it
    date = stamp.stamp_date(REPO, sha)
    top = max(_defined_adrs(_decisions_text()))
    L: list[str] = []
    A = L.append
    A("# CURRENT_AUTHORITIES.md — the current state of the completion and recovery authorities")
    A("")
    A("> **DERIVED DOCUMENT — REGENERATE, DO NOT EDIT IN PLACE.**")
    A("> Regenerate with `env -u PYTHONPATH .venv/bin/python scripts/derive_current_authorities.py`.")
    A("> It states the **current** state, not history: it cites ADRs, it does not re-derive them, and it")
    A("> **introduces no decision**. If two ADRs conflict, that is a **finding** (recorded in §5), never a")
    A("> decision taken here.")
    A(">")
    A("> **Every claim below carries a pin**: `ADR-XXXX §Y` for the decision, and `path:line` for the code.")
    A("> The generator **checks every pin against the tree** and **generates §3 from `goal.PRECEDENCE`**; a")
    A("> pin that does not name its symbol, a row the arbiter does not return, or an ADR chain that omits an")
    A("> ADR superseding one it cites **refuses the derivation**. §5 is this page's own findings record —")
    A("> **append-only**, emitted unchanged (ADR-0062 R8).")
    A(">")
    A(f"> Generated {date} at `{sha}` · covers **ADR-0001 … ADR-{top:04d}** · supersession chains in §1.1–1.6.")
    A("> The commit, the date and the range are **read from `git` and the ADR log**, not written (F97).")
    A(">")
    A("> **Sibling registers:** `CURRENT_FINDINGS.md`, `CURRENT_OPEN_ITEMS.md`, `CURRENT_FLAGS.md` — all")
    A("> derived; none may decide. See `CONTEXT.md`'s **\"The derived registers\"**.")
    A("")
    A("---")
    A("")
    A("## 1. The six authorities")
    A("")
    A("The chain is **one-way**. Each authority may consume a lower one; none may re-decide a higher one's question.")
    A("")
    A(CHAIN_DIAGRAM)
    for heading, owner, cannot, adrs, fields in AUTHORITIES:
        A("")
        A(f"### {heading}")
        A("")
        A("| | |")
        A("|---|---|")
        A(f"| **Current owner** | {owner} |")
        A(f"| **Cannot decide** | {cannot} |")
        A(f"| **Current ADRs** | {adrs} |")
        A(f"| **Durable record fields** | {fields} |")
    for block in (SECTION_2, render_matrix(), SECTION_4, SECTION_5.rstrip("\n"), SECTION_6):
        A("")
        A("---")
        A("")
        A(block)
    A("")
    return "\n".join(L)


def main() -> int:
    problems = _check()
    if problems:
        print("DERIVATION REFUSED — the page's sources are not sound:", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)
        return 2
    page = render()
    OUT.write_text(page, encoding="utf-8")
    print(f"wrote {OUT.name}: {len(AUTHORITIES)} authorities, {len(_precedence())} matrix rows, "
          f"{len(PIN_RE.findall(page))} pins checked")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
